### ISSUE TITLE
[Question] Webhook for async PDF generation

### ISSUE THREAD

**Issue by joemasilotti** [DocRaptor/docraptor-ruby#16]
Hello. I was wondering if there are any plans to POST to a webhook when generating a PDF via `async_doc`. That would simplify a lot of error handling and looping on the client side.

**Comment by janxious** [comment]
We have that already, or should. Check out the [`callback_url` attribute](https://github.com/DocRaptor/docraptor-ruby/blob/b50a8ce235a5742afd729c7f24c9e30da6876f62/lib/docraptor/models/doc.rb#L100). The DocRaptor API documentation is [here](https://docraptor.com/documentation/api#api_callback_url).

**Comment by joemasilotti** [comment]
Ah, perfect! Thank you.
