### ISSUE TITLE
Typhoeus dependency

### ISSUE THREAD

**Issue by jimmybaker** [DocRaptor/docraptor-ruby#4]
Typhoeus is now at 1.0.2 and is widely popular. Why is this gem depending on such an old version?

https://github.com/DocRaptor/docraptor-ruby/blob/master/docraptor.gemspec#L16

**Comment by janxious** [comment]
We're depending on swagger to do code generation across several clients, and at the time we released this it was locked on that version, probably. I'll take a look at the current stuff and update as necessary or pull in the PR you opened if it doesn't break the code generation compatibility. Thanks for reporting! 😸

**Comment by alto** [comment]
+1

**Comment by janxious** [comment]
@alto @jimmybaker Sorry for leaving this one dead for so long. There is a beta cut based on #14 here: https://rubygems.org/gems/docraptor/versions/1.2.0beta1

We'll probably have it non-beta released once we do some more testing internally which should be wrapped up next week if all goes well.

**Comment by janxious** [comment]
This is now fixed by [v1.2.0](https://rubygems.org/gems/docraptor/versions/1.2.0)

**Comment by alto** [comment]
@janxious Great, thanks a lot!
